FROM node:20.4.0-alpine

WORKDIR /nuxt

RUN apk update && apk upgrade
RUN apk add git

COPY ["package.json", "yarn.lock", "/nuxt/"]
RUN yarn install
COPY . .

# ENV PATH ./node_modules/.bin/:$PATH