http:
  routers:
    couchdb:
      entryPoints: 
      - http
      service: couchdb-service
      rule: Host(`couchdb.{{ env "BASE_DOMAIN" }}`)

  services:
    couchdb-service:
      loadBalancer:
        servers:
        - url: http://couchdb-node1:5984/
        - url: http://couchdb-node2:5984/
        - url: http://couchdb-node3:5984/
        passHostHeader: false