http:
  routers:
    couchdb:
      entryPoints: 
      - http
      service: couchdb-service
      rule: Host(`couchdb.otter.lt`) || Host(`couchdb.internal`)

  services:
    couchdb-service:
      loadBalancer:
        servers:
        - url: http://172.16.238.20:5984/
        - url: http://172.16.238.21:5984/
        - url: http://172.16.238.22:5984/
        passHostHeader: false