http:
  routers:
    frontend:
      entryPoints: 
      - http
      service: frontend-service
      rule: Host(`{{ env "BASE_DOMAIN" }}`) || Host(`www.{{ env "BASE_DOMAIN" }}`)

  middlewares:
    frontend-middleware:
      buffering:
        # Limite by 256KB | TODO: Update limits
        maxRequestBodyBytes: 256000

  services:
    frontend-service:
      loadBalancer:
        servers:
        # - url: http://172.16.238.11:3000/ # PROD
        # - url: http://172.16.238.12:3000/ # PROD
        - url: http://172.16.238.13:3000/ # DEV
        passHostHeader: false