http:
  routers:
    kafka:
      entryPoints: 
      - http
      service: kafka-service
      rule: Host(`kafka.{{ env "BASE_DOMAIN" }}`)

  services:
    kafka-service:
      loadBalancer:
        servers:
        - url: http://queue-ui:8080/
        passHostHeader: false